services:
    hyperbolaa_ueditor:
        class: Hyperbolaa\Ueditor\Service\UeditorService
        calls:
            - [ setContainer, [ @service_container ] ]

    hyperbolaa_ueditor.twig.hyperbolaa_ueditor_extension:
        class: Hyperbolaa\Ueditor\Twig\HyperbolaaUeditorExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setContainer, [ @service_container ] ]
